# f = open('a1.txt','x')
# print("File Created")
f= open('a1.txt','w')
f.write("================== This is Python class=========================")
data=('My Name is Adnan Farooqui\n','I Am from Bhopal MP\n','I Did My Graduation From BSSS College Bhopal\n')
f.writelines(data)
print(f.writable())
f= open('a1.txt','r')
print(f.mode)
data=f.read(10)
data1=f.readline()
data2=f.readlines()
print(data)
print(data1)
print(data2)
print(f.read(10))
print(f.readlines())
print(f.readable())
f.read()
f.readline()
f.readlines()
f=open('a1.txt','a')
f.write("This is Append Mode")
f.close()